apiVersion: apps/v1
kind: Deployment
metadata:
  name: clone
  namespace: names-clone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clone
  template:
    metadata:
      labels:
        app: clone
    spec:
      containers:
        - name: clone
          image: "brenhe/hello-world-api:beebd3ebc445eb69973045d892841c74a5a84da8"
          ports:
            - containerPort: 3005
