apiVersion: v1
kind: Service
metadata:
  name: clone-service
  namespace: names-clone
spec:
  selector:
    app: clone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3005
  type: NodePort