apiVersion: v1
kind: Service
metadata:
  name: clone-service
  namespace: app2-com-argo
spec:
  selector:
    app: clone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: NodePort