name: Automatico main to main

on:
  push:
    branches: [main]

jobs:
  push_automatico_main_to_main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Push to backup repo
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -t ed25519 -C "automate@teste.com" -f ~/.ssh/id_ed25519 -N ""
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          git remote add backup git@github.com:brenhe/infrapdv2.git
          git push backup main
