name: Automatico main to main

on:
  push:
    branches: [main]

jobs:
  push_automatico_main-to-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Push to backup repo
        run: |
          git config user.name "automate"
          git remote add backup https://github.com/brenhe/infrapdv2.git
          git push backup main