name: Automatico main to main

on:
  push:
    branches: [main]

jobs:
  push_automatico_main_to_main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Push to backup repo
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote add backup git@github.com:brenhe/infrapdv2.git
          git push backup main