name: Automatico main to main

on:
  push:
    branches: [main]

jobs:
  push_automatico_main_to_main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Push to backup repo
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "automate"
          git config user.email "automate@teste.com"
          git remote add backup https://x-access-token:${GH_PAT}@github.com/brenhe/infrapdv2.git
          git push backup main