name: Automatico main to main

on:
  push:
    branches: [main]

jobs:
  push_automatico_main_to_main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

      - name: Push to backup repo
        run: |
          git remote add backup git@github.com:brenhe/infrapdv2.git
          git push backup main --force

