name: Check Commit ARGOCD

on:
  workflow_dispatch:

jobs:
  check-argocd-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Obter hash do commit atual do GitHub
        id: get-git-hash
        run: echo "hash_github=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Instalar Argo CD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/

      - name: Fazer login no Argo CD
        env:
          ARGOCD_SERVER: localhost:8080
          ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
        run: |
          argocd login $ARGOCD_SERVER \
            --username $ARGOCD_USERNAME \
            --password $ARGOCD_PASSWORD \
            --insecure

      - name: Obter hash do commit no Argo CD e comparar
        env:
          ARGOCD_APP_NAME: clone
        run: |
          hash_argocd=$(argocd app get $ARGOCD_APP_NAME -o json | jq -r '.status.sync.revision')
          echo "Commit no ArgoCD: $hash_argocd"
          echo "Commit no GitHub: ${{ steps.get-git-hash.outputs.hash_github }}"

          if [ "$hash_argocd" = "${{ steps.get-git-hash.outputs.hash_github }}" ]; then
            echo "✅ Commits estão sincronizados!"
          else
            echo "❌ Hash diferente! O ArgoCD ainda não aplicou o commit mais recente."
            exit 1
          fi