jobs:
  check-argocd-commit:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Login no ArgoCD
        env:
          ARGOCD_SERVER: localhost:8080
          ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
        run: |
          & "C:\Program Files (x86)\ArgoCD\argocd.exe" login $env:ARGOCD_SERVER --username $env:ARGOCD_USERNAME --password $env:ARGOCD_PASSWORD --insecure
        shell: powershell

      - name: Obter hash do commit no ArgoCD e comparar
        env:
          ARGOCD_APP_NAME: clone
          GITHUB_HASH: ${{ github.sha }}
        run: |
          $hash_argocd = & "C:\Program Files (x86)\ArgoCD\argocd.exe" app get $env:ARGOCD_APP_NAME -o json | ConvertFrom-Json | Select-Object -ExpandProperty status | Select-Object -ExpandProperty sync | Select-Object -ExpandProperty revision
          Write-Host "Commit no ArgoCD: $hash_argocd"
          Write-Host "Commit no GitHub: $env:GITHUB_HASH"
          if ($hash_argocd -eq $env:GITHUB_HASH) {
            Write-Host "✅ Commits estão sincronizados!"
          } else {
            Write-Error "❌ Hash diferente! O ArgoCD ainda não aplicou o commit mais recente."
            exit 1
          }
        shell: powershell