name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: brenhe/hello-world-api  #imagem no docker hub
      DEPLOYMENT_FILE: kubernetes/deployment.yaml

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Verificar branch e tag
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Gerar tag única
        id: tagger
        run: echo "TAG=$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build e push da imagem Docker
        run: |
          docker build -t $IMAGE_NAME:$TAG ./
          docker push $IMAGE_NAME:$TAG

      - name: Instalar yq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.15.1/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Atualizar deployment.yaml com nova tag
        run: |
          yq eval ".spec.template.spec.containers[0].image = \"$IMAGE_NAME:$TAG\"" -i $DEPLOYMENT_FILE

      - name: Commit e push do deployment.yaml atualizado
        run: |
          git diff --exit-code $DEPLOYMENT_FILE || (
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add $DEPLOYMENT_FILE
          git commit -m "Atualizar imagem para tag $TAG"
          git push
          )